"""update database

Revision ID: 0c9eb24f221f
Revises: 4b1791972076
Create Date: 2024-07-15 21:38:52.037482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9eb24f221f'
down_revision = '4b1791972076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('look_talent', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('seek_des', sa.String(length=500), nullable=True))
        batch_op.alter_column('facebook_link',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.alter_column('facebook_link',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('seek_des')
        batch_op.drop_column('look_talent')
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
