"""delete foreign key show- venue

Revision ID: 4b1791972076
Revises: 58315c6494df
Create Date: 2024-07-14 16:24:28.870898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1791972076'
down_revision = '58315c6494df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint('unique_venue_time', type_='unique')
        batch_op.drop_constraint('shows_venue_id_fkey', type_='foreignkey')
        batch_op.drop_column('venue_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('shows_venue_id_fkey', 'venue', ['venue_id'], ['id'])
        batch_op.create_unique_constraint('unique_venue_time', ['venue_id', 'time'])

    # ### end Alembic commands ###
