"""add UniqueConstranit in Show table

Revision ID: 58315c6494df
Revises: 65ff8fa28e46
Create Date: 2024-07-14 15:49:31.832187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58315c6494df'
down_revision = '65ff8fa28e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_venue_time', ['venue_id', 'time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint('unique_venue_time', type_='unique')

    # ### end Alembic commands ###
