"""update add foreign key

Revision ID: 65ff8fa28e46
Revises: 4fd5ed0d7a80
Create Date: 2024-07-13 23:37:23.890076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ff8fa28e46'
down_revision = '4fd5ed0d7a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('venue_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'venue', ['venue_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('venue_id')
        batch_op.drop_column('time')

    # ### end Alembic commands ###
