"""add columnu in table artist

Revision ID: 87d494ba3c08
Revises: f323aba683fb
Create Date: 2024-07-21 00:51:49.732781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d494ba3c08'
down_revision = 'f323aba683fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('look_talent', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('seek_des', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('seek_des')
        batch_op.drop_column('look_talent')
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
